ignore-interior-mutability = ["bytes::Bytes", "lockfree_object_pool::LinearReusable"]
disallowed-types = ["std::collections::HashMap", "std::collections::HashSet", "ahash::AHMap", "ahash::AHashSet", "ahash::AHasher", "ahash::RandomState"]
