[nodes.try_set_field]
title = "Try Set Field"
description = "Attempts to replace value of the specified field in the input object."
docs = """
#### Field detection
- If the input object is a struct and contains the specified field, that field \
will be replaced.
- If the input object is a struct that contains inline fields, the search will \
be performed recursively on inline fields.
- If the input object is an enum, the search will be performed on the enum's \
value
- Otherwise, the node return false and does not modify the object.

Unlike `Set Field` node, this node will not fail if the field does not exist \
in the input object, and will not fail if the input value is not compatible \
with the field type, it will simply return false on the `success` field.

#### Failures
- The node will fail is the input object is not a struct or enum.
"""

[[nodes.try_set_field.inputs]]
title = "Object"
id = "object"
description = "Object to modify. Must be a struct or an enum."

[[nodes.try_set_field.inputs]]
title = "Field"
id = "field"
description = "Field name to replace"

[[nodes.try_set_field.inputs]]
title = "Value"
id = "value"
description = "New value for the field"
docs = """
Value will be converted to the field type using the same logic as node port
connection. If the conversion fails, the node will return false.
"""

[[nodes.try_set_field.outputs]]
title = "Object"
id = "object"
description = "The modified object"
docs = """
Will remain unchanged if the field was not found or the conversion failed
"""

[[nodes.try_set_field.outputs]]
title = "Success"
id = "success"
description = "Success of the operation"
docs = """
Indicates whenever the field was found and the value was successfully set.
"""

[[nodes.try_set_field.outputs]]
title = "Old Value"
id = "old_value"
description = "Previous value of the field"
docs = """
This value will be None if the field was not found or the conversion failed

Returned value might have different type than the new value, in case if the \
conversion was performed
"""